version: "3.7"
services:
  datastet:
    image: grobid/datastet:0.8.0
    init: true
    ports:
      - "8060:8060"
    deploy:
      restart_policy:
        condition: any
        delay: 3s
        window: 60s
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
