version: "3.7"
services:
  grobid:
    image: grobid/grobid:0.8.0
    init: true
    ports:
      - "8070:8070"
      - "8071:8071"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

